[workspace]
members = [
    "transport",
    "crdt",
    "wasm_client",
    "wasm_server",
]

[patch.crates-io]
tonic = { git = "https://github.com/boxdot/tonic", rev = "2ed4144" }
tonic-build = { git = "https://github.com/boxdot/tonic", rev = "2ed4144" }